package tateti;

public enum Movimiento {

	ADELANTE,
	ATRAS,
	IZQUIERDA, 
	DERECHA,
	IZQUIERDA_ADELANTE,
	IZQUIERDA_ATRAS,
	DERECHA_ADELANTE,
	DERECHA_ATRAS,
	ARRIBA, 
	ABAJO,
	ADELANTE_ARRIBA,
	ADELANTE_ABAJO,
	ATRAS_ARRIBA,
	ATRAS_ABAJO,
	IZQUIERDA_ARRIBA,
	IZQUIERDA_ABAJO,
	DERECHA_ARRIBA,
	DERECHA_ABAJO,
	IZQUIERDA_ADELANTE_ARRIBA,
	IZQUIERDA_ADELANTE_ABAJO,
	DERECHA_ADELANTE_ARRIBA,
	DERECHA_ADELANTE_ABAJO,
	IZQUIERDA_ATRAS_ARRIBA,
	IZQUIERDA_ATRAS_ABAJO,
	DERECHA_ATRAS_ARRIBA,
	DERECHA_ATRAS_ABAJO
}
